### PR TITLE
make executable

### LINKED ISSUE #163: jexec: execvp: /root/post_install.sh: Permission denied
Hello, 

I'm trying to package the project [MovieNight](https://github.com/zorchenhimer/MovieNight) as an TrueNAS Plugin. I know it quite well, I had built it many times, and I run an instance on my TrueNAS. 
I had started the job to make the plugin deployment files and scripts. 
I had submitted an Pull Request during the steps. 
I'm now testing the `iocage` plugin deployment and I'm stuck in an issue. When I run `iocage fetch --plugins --git_repository https://github.com/zorglube/iocage-plugin-index.git dhcp="on" --branch master --update` I have this error `jexec: execvp: /root/post_install.sh: Permission denied` AND i don't understand why `post_install.sh` can't be run AND how to fix that. 

If anyone can help, I'll be glad you read your advises. 

Zorglube

### PR DESCRIPTION
**Pull request by tprelog**
should resolve https://github.com/ix-plugin-hub/iocage-plugin-index/issues/163 :smile:

### CODE REVIEW

**Comment by zorglube** [comment]
I don't know what solution you used, I found `git update-index --chmod=+x ./post_install.sh`

**Comment by zorglube** [comment]
By the way : Thank a lot !!!

**Comment by tprelog** [comment]
> I don't know what solution you used, I found `git update-index --chmod=+x ./post_install.sh`

I'm working from my (Linux) computer, not from the GitHub website

These are the steps I took:

First I made a fork of your repository. 

Then, from my computer I ran the following commands
```bash
git clone https://github.com/tprelog/iocage-plugin-movienight.git
cd iocage-plugin-movienight
chmod +x post_install.sh
git commit -am "make executable"
git push
```

Finally I made pull-request from my fork back to you


---


> By the way : Thank a lot !!!

No problem, I'm glad this helped :)

**Comment by zorglube** [comment]
> > I don't know what solution you used, I found `git update-index --chmod=+x ./post_install.sh`
> 
> I'm working from my (Linux) computer, not from the GitHub website

Got it, my problem is I'm working from an Windows computer, so i don't have any `chmod`. 

> 
> These are the steps I took:
> 
> First I made a fork of your repository.
> 
> Then, from my computer I ran the following commands
> 
> ```shell
> git clone https://github.com/tprelog/iocage-plugin-movienight.git
> cd iocage-plugin-movienight
> chmod +x post_install.sh
> git commit -am "make executable"
> git push
> ```
> 
> Finally I made pull-request from my fork back to you

I definitely know the steps you went through. I mean I'm no sys-admin but I know about `chmod`. 
I was just thinking that `Git` didn't carry the file 'acces right' 

> 
> > By the way : Thank a lot !!!
> 
> No problem, I'm glad this helped :)

You know what... You helped me, and I made few edition on the file and it lost it's execution attribut -____-"

**Pull request merged**
